export const ORDER_STATUSES = {
  PEDIDO_RECIBIDO: 'PEDIDO_RECIBIDO',
  PREPARANDO_ENVIO: 'PREPARANDO_ENVIO',
  EN_CAMINO: 'EN_CAMINO',
  ENTREGADO: 'ENTREGADO',
}

export const ORDER_STATUS_SEQUENCE = [
  ORDER_STATUSES.PEDIDO_RECIBIDO,
  ORDER_STATUSES.PREPARANDO_ENVIO,
  ORDER_STATUSES.EN_CAMINO,
  ORDER_STATUSES.ENTREGADO,
]

export const ORDER_STATUS_LABELS = {
  [ORDER_STATUSES.PEDIDO_RECIBIDO]: 'Pedido recibido',
  [ORDER_STATUSES.PREPARANDO_ENVIO]: 'Preparando envío',
  [ORDER_STATUSES.EN_CAMINO]: 'En camino',
  [ORDER_STATUSES.ENTREGADO]: 'Entregado',
}
