export const ORDER_STATUSES = {
  PEDIDO_RECIBIDO: 'PEDIDO_RECIBIDO',
  PREPARANDO_ENVIO: 'PREPARANDO_ENVIO',
  EN_CAMINO: 'EN_CAMINO',
  ENTREGADO: 'ENTREGADO',
}

export const ORDER_STATUS_VALUES = Object.values(ORDER_STATUSES)
